//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estructura.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaUnion
    {
        public int EmpleadoID { get; set; }
        public string Nombre { get; set; }
        public int PuestoID { get; set; }
        public string DescripcionPuesto { get; set; }
        public int DepartamentoId { get; set; }
        public string DescripcionDepartamento { get; set; }
    }
}
